// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comment.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (task_id , author_id , body)
Values ($1 , $2 , $3)
RETURNING id, task_id, author_id, body, created_at, updated_at, deleted_at
`

type CreateCommentParams struct {
	TaskID   uuid.UUID `json:"task_id"`
	AuthorID uuid.UUID `json:"author_id"`
	Body     string    `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.TaskID, arg.AuthorID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, task_id, author_id, body, created_at, updated_at, deleted_at FROM comments
WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCommentsByTask = `-- name: ListCommentsByTask :many
SELECT c.id, c.task_id, c.author_id, c.body, c.created_at, c.updated_at, c.deleted_at , u.full_name , u.email
FROM comments c
JOIN users u ON u.id = c.author_id
WHERE c.task_id= $1
ORDER BY c.created_at ASC
`

type ListCommentsByTaskRow struct {
	ID        uuid.UUID          `json:"id"`
	TaskID    uuid.UUID          `json:"task_id"`
	AuthorID  uuid.UUID          `json:"author_id"`
	Body      string             `json:"body"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	FullName  string             `json:"full_name"`
	Email     string             `json:"email"`
}

func (q *Queries) ListCommentsByTask(ctx context.Context, taskID uuid.UUID) ([]ListCommentsByTaskRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByTaskRow{}
	for rows.Next() {
		var i ListCommentsByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FullName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE comments
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteComment, id)
	return err
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET body = $2 , updated_at = now()
WHERE id = $1
RETURNING id, task_id, author_id, body, created_at, updated_at, deleted_at
`

type UpdateCommentParams struct {
	ID   uuid.UUID `json:"id"`
	Body string    `json:"body"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
