// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (project_id , sender_id , body)
Values ($1 , $2 , $3)
RETURNING id, project_id, sender_id, body, created_at, updated_at, deleted_at
`

type CreateMessageParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	SenderID  uuid.UUID `json:"sender_id"`
	Body      string    `json:"body"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ProjectID, arg.SenderID, arg.Body)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SenderID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, project_id, sender_id, body, created_at, updated_at, deleted_at FROM messages
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SenderID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMessagesByProject = `-- name: ListMessagesByProject :many
SELECT m.id, m.project_id, m.sender_id, m.body, m.created_at, m.updated_at, m.deleted_at , u.full_name , u.email
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE m.project_id = $1
    AND m.deleted_at IS NULL
    AND ($2::timestamptz IS NULL OR m.created_at < $2)
ORDER BY m.created_at DESC
LIMIT $3
`

type ListMessagesByProjectParams struct {
	ProjectID uuid.UUID          `json:"project_id"`
	Limit     int32              `json:"limit"`
	Before    pgtype.Timestamptz `json:"before"`
}

type ListMessagesByProjectRow struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	SenderID  uuid.UUID          `json:"sender_id"`
	Body      string             `json:"body"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	FullName  string             `json:"full_name"`
	Email     string             `json:"email"`
}

func (q *Queries) ListMessagesByProject(ctx context.Context, arg ListMessagesByProjectParams) ([]ListMessagesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByProject, arg.ProjectID, arg.Before, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesByProjectRow{}
	for rows.Next() {
		var i ListMessagesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SenderID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FullName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMessage = `-- name: SoftDeleteMessage :exec
UPDATE messages
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteMessage, id)
	return err
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages
SET body = $2 , updated_at = now()
WHERE id = $1
RETURNING id, project_id, sender_id, body, created_at, updated_at, deleted_at
`

type UpdateMessageParams struct {
	ID   uuid.UUID `json:"id"`
	Body string    `json:"body"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessage, arg.ID, arg.Body)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SenderID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
