// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package sqlc

import (
	"context"
)

const anyOrganizationExists = `-- name: AnyOrganizationExists :one
SELECT EXISTS (SELECT 1 FROM organizations)
`

func (q *Queries) AnyOrganizationExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, anyOrganizationExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name ,slug)
VALUES($1 , $2)
RETURNING id, name, slug, created_at, updated_at, deleted_at
`

type CreateOrganizationParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, created_at, updated_at, deleted_at FROM organizations
WHERE slug= $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
