// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (organization_id , name , description)
VALUES ($1 , $2 , $3)
RETURNING id, organization_id, name, description, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OrganizationID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, organization_id, name, description, created_at, updated_at, deleted_at FROM projects 
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjectsByOrganization = `-- name: ListProjectsByOrganization :many
SELECT id, organization_id, name, description, created_at, updated_at, deleted_at FROM projects 
WHERE organization_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProject, id)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects 
SET name = $2 , description = $3 , updated_at = now()
WHERE id = $1
RETURNING id, organization_id, name, description, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
