// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error)
	AnyUserExists(ctx context.Context) (bool, error)
	AssignTaskToUser(ctx context.Context, arg AssignTaskToUserParams) (Task, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectMemberRole(ctx context.Context, arg GetProjectMemberRoleParams) (string, error)
	GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListCommentsByTask(ctx context.Context, taskID uuid.UUID) ([]ListCommentsByTaskRow, error)
	ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListTasksAssignedToUser(ctx context.Context, assignedToUserID pgtype.UUID) ([]Task, error)
	ListTasksByProject(ctx context.Context, projectID uuid.UUID) ([]Task, error)
	ListUsers(ctx context.Context) ([]User, error)
	RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error
	SoftDeleteComment(ctx context.Context, id uuid.UUID) error
	SoftDeleteProject(ctx context.Context, id uuid.UUID) error
	SoftDeleteTask(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UnassignTask(ctx context.Context, id uuid.UUID) (Task, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
