// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) (OrganizationMember, error)
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetOrganizationMemberRole(ctx context.Context, arg GetOrganizationMemberRoleParams) (string, error)
	GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamMemberRole(ctx context.Context, arg GetTeamMemberRoleParams) (string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error)
	ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error)
	ListTeamsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Team, error)
	RemoveOrganizationMember(ctx context.Context, arg RemoveOrganizationMemberParams) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	SoftDeleteTeam(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
