// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignTaskToUser = `-- name: AssignTaskToUser :one
UPDATE tasks
SET assigned_to_user_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, project_id, title, description, status, priority, assigned_to_user_id, due_date, created_by, created_at, updated_at, deleted_at
`

type AssignTaskToUserParams struct {
	ID               uuid.UUID   `json:"id"`
	AssignedToUserID pgtype.UUID `json:"assigned_to_user_id"`
}

func (q *Queries) AssignTaskToUser(ctx context.Context, arg AssignTaskToUserParams) (Task, error) {
	row := q.db.QueryRow(ctx, assignTaskToUser, arg.ID, arg.AssignedToUserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedToUserID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, description, priority, due_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, title, description, status, priority, assigned_to_user_id, due_date, created_by, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Priority    string             `json:"priority"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	CreatedBy   uuid.UUID          `json:"created_by"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DueDate,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedToUserID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, project_id, title, description, status, priority, assigned_to_user_id, due_date, created_by, created_at, updated_at, deleted_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedToUserID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTasksAssignedToUser = `-- name: ListTasksAssignedToUser :many
SELECT id, project_id, title, description, status, priority, assigned_to_user_id, due_date, created_by, created_at, updated_at, deleted_at FROM tasks
WHERE assigned_to_user_id = $1
ORDER BY due_date ASC NULLS LAST
`

func (q *Queries) ListTasksAssignedToUser(ctx context.Context, assignedToUserID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksAssignedToUser, assignedToUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssignedToUserID,
			&i.DueDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, project_id, title, description, status, priority, assigned_to_user_id, due_date, created_by, created_at, updated_at, deleted_at FROM tasks
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTasksByProject(ctx context.Context, projectID uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssignedToUserID,
			&i.DueDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTask, id)
	return err
}

const unassignTask = `-- name: UnassignTask :one
UPDATE tasks
SET assigned_to_user_id = NULL, updated_at = now()
WHERE id = $1
RETURNING id, project_id, title, description, status, priority, assigned_to_user_id, due_date, created_by, created_at, updated_at, deleted_at
`

func (q *Queries) UnassignTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, unassignTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedToUserID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $2, description = $3, priority = $4, due_date = $5, updated_at = now()
WHERE id = $1
RETURNING id, project_id, title, description, status, priority, assigned_to_user_id, due_date, created_by, created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Priority    string             `json:"priority"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedToUserID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, project_id, title, description, status, priority, assigned_to_user_id, due_date, created_by, created_at, updated_at, deleted_at
`

type UpdateTaskStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedToUserID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
