// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (organization_id , name)
VALUES($1 , $2)
RETURNING id, name, organization_id, created_at, updated_at, deleted_at
`

type CreateTeamParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.OrganizationID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, organization_id, created_at, updated_at, deleted_at FROM teams 
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTeamsByOrganization = `-- name: ListTeamsByOrganization :many
SELECT id, name, organization_id, created_at, updated_at, deleted_at FROM teams 
WHERE organization_id = $1
`

func (q *Queries) ListTeamsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTeam = `-- name: SoftDeleteTeam :exec
UPDATE teams
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTeam, id)
	return err
}
